# wrangler.toml
name = "up-or-down-check-api"              # a unique slug for your Worker
main = "src/api/check.js"                  # where your code lives
compatibility_date = "2025-05-25"          # YYYY-MM-DD

account_id = "6654feab59802e1fe9efcc16da4e8327"        # paste from Dashboard
zone_id    = "82593d6c2c09263683ff7eec4b49d541"           # paste from Dashboard

# Route binding: forward all /api/* calls on your domain to this Worker
[[routes]]
pattern = "upordowncheck.com/api/*"
zone_id = "82593d6c2c09263683ff7eec4b49d541"
